apiVersion: v1
kind: ConfigMap
metadata:
  name: team-service-devconfig
data:
  PORT: "4003"
  MONGO_URL: "mongodb://admin:password123@mongo-service.dev.svc.cluster.local:27017/team_db?authSource=admin"
  REDIS_URL: "redis://redis-service.dev.svc.cluster.local:6379"
